name: dart_everybody_codes_2024
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-180.3.beta

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.19.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
